<?php $requete=odbc_exec($bdd,"
SELECT QPM_SITE,QPM_GRP,QPM_SAISON,QPM_ARTTECH,QPM_PHASE,QPM_LIEUPOLE,
	QPM_LIEUSITE,QPM_LIEUGRP,QAR_ARTTECHLIB,QEP_QTOUPERIODE,QPM_ORDFAB,QEP_TRANCHE,
	QPM_DATEDEBUT,QPM_DATEFIN,QPM_CONTENU,QPM_QTAFAIRE, QPM_DUREEPHASE/360 AS DUREEPHASE,
	QAF_GROUPOF,QAF_DATEDEBDEMANDE,QAF_DATEFINDEMANDE,QAF_DATEDEBCONF,QAF_DATEFINCONF,
	QAF_DATEDEBCONST,QAF_DATEFINCONST,QEP_CARPROD,QLA_DATEDEBUT,QLA_DATEFIN,QLA_TYPEOF,
	QLA_SAISONOF,QLA_DEVISE,QLA_INCOTERM,QLA_LIGCOMMANDE,QLA_MODEPAIE,QLA_MODEREGLE,QLA_MONTANT,
	QLA_NUMCDECLIENT,QLA_NUMCOMMANDE,QMG_COEFUNITECAD,QMG_CODUNI,QMG_TYPEOPE, QGR_CHAINEORDO
FROM QPLANGP 
LEFT JOIN QARTTECH ON QAR_CTX='0' AND QAR_SAISON=QPM_SAISON AND QAR_ARTTECH=QPM_ARTTECH 
LEFT JOIN QEPLAN ON QEP_CTX='300' AND QEP_SITE=QPM_SITE AND QEP_GRP=QPM_GRP AND QEP_INDX=QPM_INDX 
LEFT JOIN QAFFECTOF ON QAF_CTX='0' AND QAF_ORDFAB=QPM_ORDFAB AND QAF_OPEITI=QPM_OPEITI 
LEFT JOIN QLANCEMEN ON QLA_CTX='0' AND QLA_ORDFAB=QPM_ORDFAB 
LEFT JOIN QGROUPE on QGR_GRP=QPM_LIEUGRP and QPM_CTX='300' and QGR_CTX='0'
LEFT JOIN QMACROGAM ON QMG_CTX='0' AND QMG_SAISON=QPM_SAISON AND QMG_ARTTECH=QPM_ARTTECH
AND QMG_COLORIS='%' AND QMG_OPEGAM=QPM_OPEITI 
WHERE QPM_CTX='300' AND ((QPM_PHASE='TRE') AND (QPM_ORDFAB <> ' ' ))
order by QPM_LIEUGRP, QLA_DATEFIN
 "); ?>