SELECT (GL_TIERS) as CLIENT, T1.T_LIBELLE as RAISONSOCIALE, GL_NUMERO as ARC, GL_NUMLIGNE as LIG, GL_CODEARTICLE as CODEARTICLE, GL_LIBELLE as LIBELLE, GL_DATELIVRAISON as LIVRAISON,  GL_QTEFACT as QTE, GL_QTERESTE as RAL,

( select top 1 (QPM_DUREEPHASE/360)/QPM_QTAFAIRE from QPLANGP where QPM_ARTTECH=GL_ARTICLE and QPM_CTX like "002" and QPM_PHASE Like "MON" )* GL_QTERESTE as HEURES,